ci: only run test for now

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -102,58 +102,58 @@ jobs:
     #       done
     #     fi
 
-  quickstart:
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-        - ubuntu-latest
-        - macos-latest
-
-    runs-on: ${{matrix.os}}
-    steps:
-    - uses: ocaml/setup-ocaml@v3
-      name: Use OCaml
-      if: runner.os != 'Windows'
-      with:
-        ocaml-compiler: ${{matrix.ocaml}}
-    - name: Quick start
-      run: |
-        set -x
-        touch output
-        tail -f output | grep --line-buffered 'Ctrl' | xargs -L1 -I FOO bash -c "echo Success && touch success && killall middleware.exe" &
-        tail -f output &
-        ((curl -fsSL https://raw.githubusercontent.com/aantron/dream/$GITHUB_SHA/example/quickstart.sh | bash -s $GITHUB_SHA) || true) > output 2>&1
-        sleep 1
-        if [ -f success ]
-        then
-          exit 0
-        else
-          exit 1
-        fi
-
-  mirage:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        submodules: recursive
-    - run: mkdir ../repo-copy
-    - run: cp -r * ../repo-copy/
-    - uses: ocaml/setup-ocaml@v3
-      with:
-        ocaml-compiler: 4.14.x
-    - run: opam install --yes --deps-only ./dream-pure.opam ./dream-httpaf.opam ./dream.opam ./dream-mirage.opam
-    - run: opam install --yes mirage mirage-clock-unix
-    - run: cd example/w-mirage && mv config.ml config.ml.backup
-    - run: cd example/w-mirage && sed -e 's/package "dream-mirage"//' < config.ml.backup > config.ml
-    - run: cd example/w-mirage && opam exec -- mirage configure -t unix
-    - run: cd example/w-mirage && opam exec -- make depends
-    - run: cd example/w-mirage && ls duniverse
-    - run: cp -r ../repo-copy example/w-mirage/duniverse/dream
-    - run: cd example/w-mirage/duniverse && rm -rf ocaml-cstruct logs ke fmt lwt bytes seq mirage-flow sexplib0 ptime tls domain-name ocaml-ipaddr mirage-clock ocplib-endian
-    - run: cd example/w-mirage && mv config.ml.backup config.ml
-    - run: cd example/w-mirage && sed -e 's/(libraries/(libraries dream-mirage/' < dune.build > dune.build.2
-    - run: cd example/w-mirage && mv dune.build.2 dune.build
-    - run: cd example/w-mirage && opam exec -- dune build
-    - run: file example/w-mirage/_build/default/main.exe
+  # quickstart:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #       - ubuntu-latest
+  #       - macos-latest
+  #
+  #   runs-on: ${{matrix.os}}
+  #   steps:
+  #   - uses: ocaml/setup-ocaml@v3
+  #     name: Use OCaml
+  #     if: runner.os != 'Windows'
+  #     with:
+  #       ocaml-compiler: ${{matrix.ocaml}}
+  #   - name: Quick start
+  #     run: |
+  #       set -x
+  #       touch output
+  #       tail -f output | grep --line-buffered 'Ctrl' | xargs -L1 -I FOO bash -c "echo Success && touch success && killall middleware.exe" &
+  #       tail -f output &
+  #       ((curl -fsSL https://raw.githubusercontent.com/aantron/dream/$GITHUB_SHA/example/quickstart.sh | bash -s $GITHUB_SHA) || true) > output 2>&1
+  #       sleep 1
+  #       if [ -f success ]
+  #       then
+  #         exit 0
+  #       else
+  #         exit 1
+  #       fi
+  #
+  # mirage:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #     with:
+  #       submodules: recursive
+  #   - run: mkdir ../repo-copy
+  #   - run: cp -r * ../repo-copy/
+  #   - uses: ocaml/setup-ocaml@v3
+  #     with:
+  #       ocaml-compiler: 4.14.x
+  #   - run: opam install --yes --deps-only ./dream-pure.opam ./dream-httpaf.opam ./dream.opam ./dream-mirage.opam
+  #   - run: opam install --yes mirage mirage-clock-unix
+  #   - run: cd example/w-mirage && mv config.ml config.ml.backup
+  #   - run: cd example/w-mirage && sed -e 's/package "dream-mirage"//' < config.ml.backup > config.ml
+  #   - run: cd example/w-mirage && opam exec -- mirage configure -t unix
+  #   - run: cd example/w-mirage && opam exec -- make depends
+  #   - run: cd example/w-mirage && ls duniverse
+  #   - run: cp -r ../repo-copy example/w-mirage/duniverse/dream
+  #   - run: cd example/w-mirage/duniverse && rm -rf ocaml-cstruct logs ke fmt lwt bytes seq mirage-flow sexplib0 ptime tls domain-name ocaml-ipaddr mirage-clock ocplib-endian
+  #   - run: cd example/w-mirage && mv config.ml.backup config.ml
+  #   - run: cd example/w-mirage && sed -e 's/(libraries/(libraries dream-mirage/' < dune.build > dune.build.2
+  #   - run: cd example/w-mirage && mv dune.build.2 dune.build
+  #   - run: cd example/w-mirage && opam exec -- dune build
+  #   - run: file example/w-mirage/_build/default/main.exe
